name: Install via Nix and Test
on:
  pull_request:
  push:
jobs:

  build-and-test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: [38]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Enable Cachix binary cache
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install # Developers should prefer installation via home-manager
          cachix use jacg-next-exp
      - name: Install dependencies via Nix
        run: nix-shell --argstr py ${{ matrix.py }}
